### ISSUE TITLE
Napraviti Style Guide zajednice

### ISSUE THREAD

**Issue by Facyber** [Facyber/mozilla-srbija#1]
Formirati Style Guide (vodič za lokalizaciju) zajednice za lokalizaciju, koji će služiti trenutnim i novim članovima kao uputstva kako se prevode određene stvari, terminologija reči, usvojeni prevodi brendova, imena, opcija, itd.

Napraviti spisak najčešće korišćenih reči koje se u modernom izgovoru ne koriste na engleskom jeziku, ali ne i u stručnom i formirati mini rečnik na osnovu tog spiska koji će biti uključen u vodič.

**Comment by kostich** [comment]
Да ли у Понтону можемо сачувати новонаправљену терминологију тако да је нови чланови могу претраживати и налазити српске изразе за дате енглеске? Да ли је ова могућност уведена у новом Понтону?

Што се тиче мини-речника, предлажем да користимо материјал из [Сверачунарског појмовника](http://sverapoj.nedohodnik.net/gloss/) приликом стварања.

Предлажем коришћење [Маркдауна](https://en.wikipedia.org/wiki/Markdown) за преводилачке смернице. Маркдаун је лако претворити у разноразне формате типа ПДФ, ОДТ и слично.

**Comment by kostich** [comment]
[Стари Гномов приручник за превођење](https://github.com/Facyber/mozilla-srbija/files/821997/pravopis-gnom.pdf). Може нам послужити као инспирација.

**Comment by Facyber** [comment]
Nisam siguran za to, zato bih i želeo da u naš vodiš iz tih razloga uključimo mini rečnik najčešće korišćenih reči koje prevodimo stručno, a u govoru se svakodnevno češće izgovaraju na engleskom. Staviću u TODO sekciju da pitamo nekog tamo kada stignemo da li ima i da li će biti te mogućnosti.

Možemo koristiti taj rečnik a imamo i [Mikro knjiga rečnik](http://www.mikroknjiga.rs/pub/rmk/) koji me je odlično služio od početka volontiranja, pa ćemo kombinovati ta dva.

Može, obožavam Markdow i on će se svakako koristii na Wiki stranici, a ovako možemo pisati u Libre-u pa export u PDF ili neki Markdown editor pa u pdf. Baš sam nedavno čitao o nekima, taman ću imati i priliku da ih isprobam.

Prelistaću priručnik ovih dana pa ću videti šta će nam dobro doći da iskoristimo za naš vodič.

**Comment by Facyber** [comment]
Mare kad budeš mogao baci oko na ovaj Markdown editor, izgleda mi skroz kul i ima mogućnost povezivanja sa GitHub-om, možeš da praviš grane, zajednički rad podržava, a može i bez naloga da radi što je isto odlično. Verovatno ću njega koristiti za pisanje vodiča. :) 

https://www.gitbook.com/

**Comment by kostich** [comment]
Фино изгледа. Ја ћу користити Гномовог Градитеља ([Gnome Builder](https://wiki.gnome.org/Apps/Builder)). Ево како изгледа у акцији:

![2017-03-19 21-53-56](https://cloud.githubusercontent.com/assets/4953862/24084684/24b1fd88-0cef-11e7-926c-a3ae82823348.png)

**Comment by Facyber** [comment]
Evo našao sam [bug za terminologiju](https://bugzilla.mozilla.org/show_bug.cgi?id=1243140). Sve u svemu možemo napraviti još jedan projekat ovde samo za rečnik kojem ćemo s vremena na vreme dodavati nove reči i odrediti da tipa jednom mesečno (zavisno od toga koliko često budemo dodavali) sve nove reči dodamo u vodič i tako dalje. 

Ako ubace rečnik, onda ćemo taj projekat koristiti za predloge, daš predlog, složimo se, prihvatimo i teramo dalje.

**Comment by Facyber** [comment]
Style Guide završen. Zatvaram diskusiju.
